### ISSUE TITLE
Problem with compilation with maven

### ISSUE THREAD

**Issue by pablovidelayanez** [sinfonier-project/sinfonier-backend#2]
Hi !, i try to compile and install the sinfonier-backend following the instruction of the Sinfonier book (0xword), and the instruction appears in this "readme" too, i try the compilation with the command : 

> /usr/local/maven/bin/mvn -f /var/storm/src/sinfonier-backend/pom.xml clean compile install

I have this version of java : 

> java version "1.7.0_91"
> OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-1)
> OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

and this is the output with the errors...
Thanks in advance.

> [WARNING] COMPILATION WARNING : 
> [INFO] -------------------------------------------------------------
> [WARNING] /var/storm/src/sinfonier-backend/src/jvm/com/sinfonier/bolts/BaseSinfonierBolt.java: Some input files use unchecked or unsafe operations.
> [WARNING] /var/storm/src/sinfonier-backend/src/jvm/com/sinfonier/bolts/BaseSinfonierBolt.java: Recompile with -Xlint:unchecked for details.
> [INFO] 2 warnings 
> [INFO] -------------------------------------------------------------
> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR : 
> [INFO] -------------------------------------------------------------
> [ERROR] /var/storm/src/sinfonier-backend/src/jvm/com/sinfonier/bolts/FlatJson.java:[63,9] cannot find symbol
>   symbol:   method setJSon(java.util.Map<java.lang.String,java.lang.Object>)
>   location: class com.sinfonier.bolts.FlatJson
> [INFO] 1 error
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 5.696 s
> [INFO] Finished at: 2016-07-31T16:31:38-04:00
> [INFO] Final Memory: 22M/54M
> [INFO] ------------------------------------------------------------------------
> [**ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project sinfonier: Compilation failure
> [ERROR] /var/storm/src/sinfonier-backend/src/jvm/com/sinfonier/bolts/FlatJson.java:[63,9] cannot find symbol
> [ERROR] symbol:   method setJSon(java.util.Map<java.lang.String,java.lang.Object>)
> [ERROR] location: class com.sinfonier.bolts.FlatJson**
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by pablovidelayanez** [comment]
The error was a S, change setJSon by setJson

> [ERROR] /var/storm/src/sinfonier-backend/src/jvm/com/sinfonier/bolts/FlatJson.java:[63,9] cannot find symbol 
> [ERROR] symbol: method setJSon(java.util.Map)

and now 

> s/3.0.5/plexus-utils-3.0.5.jar (226 KB at 260.5 KB/sec)
> [INFO] Installing /var/storm/lastjar/sinfonier-community-1.0.0.jar to /root/.m2/repository/com/sinfonier/sinfonier/1.0.0/sinfonier-1.0.0.jar
> [INFO] Installing /var/storm/src/sinfonier-backend/pom.xml to /root/.m2/repository/com/sinfonier/sinfonier/1.0.0/sinfonier-1.0.0.pom
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 01:58 min
> [INFO] Finished at: 2016-07-31T16:56:32-04:00
> [INFO] Final Memory: 32M/107M
> [INFO] ------------------------------------------------------------------------

**Comment by ffr4nz** [comment]
Thanks!
